channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=23.0.1
- pip:
  - mlflow==2.3
  - cloudpickle==2.2.1
  - numpy==1.23.1
  - psutil==5.9.0
  - scikit-learn==1.2.2
  - scipy==1.10.0
name: mlflow-env
